[tool.pytest.ini_options]
minversion = "7.1"
addopts = ["--last-failed", "--failed-first", "--new-first", "--maxfail=2", "--color=yes", "--cov-report=term", "--cov-report=html", "--cov-report=xml", "--cov-branch", "--cov=server"]
testpaths = ["test"]
required_plugins = ["pytest-cov", "pytest-mock"]
filterwarnings = ["ignore::DeprecationWarning"]