//Jenkinsfile (Declarative Pipeline)
pipeline {
    agent { docker { image 'python:latest' } }
    environment {
        VENV_NAME = "tests"
        VENV_PATH = "${WORKSPACE}/${VENV_NAME}"
        VENV_BIN_PATH = "${VENV_PATH}/bin/"
    }
    stages {
        stage ('set up venv and dependencies') {
            steps {
                sh "./jenkins/setup_dependencies.sh"
            }
        }
        stage('build') {
            steps {
                sh "${VENV_BIN_PATH}python --version"
            }
        }
        stage('python tests') {
            steps {
                sh "./jenkins/run_tests.sh"
            }
        }
        stage('teardown') {
            steps {
                sh "./jenkins/teardown_venv.sh"
            }
        }
    }
}