//Jenkinsfile (Declarative Pipeline)
void setBuildStatus(String message, String state) {
    step([
      $class: 'GitHubCommitStatusSetter',
      reposSource: [$class: 'ManuallyEnteredRepositorySource', url: 'https://github.com/Peetee06/web_engineering_hsbo_SS2022.git'],
      contextSource: [$class: 'ManuallyEnteredCommitContextSource', context: 'ci/jenkins/build-status'],
      errorHandlers: [[$class: 'ChangingBuildStatusErrorHandler', result: 'UNSTABLE']],
      statusResultSource: [ $class: 'ConditionalStatusResultSource', results: [[$class: 'AnyBuildResult', message: message, state: state]] ]
  ])
}

pipeline {
    agent { label 'ubuntu-2004' }
    environment {
        VENV_NAME = 'tests'
        VENV_PATH = "${WORKSPACE}/${VENV_NAME}"
        VENV_BIN_PATH = "${VENV_PATH}/bin/"
    }
    stages {
        stage ('set up venv and dependencies') {
            steps {
                sh "${WORKSPACE}/flask/jenkins/setup_dependencies.sh"
            }
        }
        stage('build') {
            steps {
                sh "${VENV_BIN_PATH}python --version"
                // TODO: code style check (linting)
            }
        }
        stage('python tests') {
            steps {
                sh "${WORKSPACE}/flask/jenkins/run_tests.sh"
            }
        }
        stage('collect test results') {
            steps {
                junit 'test-reports/*.xml'
            }
        }
    }
    post {
        always {
            // TODO: don't need to teardown as google cloud does so itself'
            // sh "${WORKSPACE}/flask/jenkins/teardown_venv.sh"
        }
        success {
            setBuildStatus('Build succeeded', 'SUCCESS')
        }
        failure {
            setBuildStatus('Build failed', 'FAILURE')
        }
    }
}
